
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A caravan support chatbot AI agent.
 *
 * - caravanSupportChatbot - A function that handles the chatbot interaction.
 * - CaravanSupportChatbotInput - The input type for the caravanSupportChatbot function.
 * - CaravanSupportChatbotOutput - The return type for the caravanSupportChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { staticCaravanningArticles, type AiGeneratedArticle } from '@/types/learn';

const CaravanSupportChatbotInputSchema = z.object({
  question: z.string().describe('The question asked by the user about caravanning.'),
});
export type CaravanSupportChatbotInput = z.infer<typeof CaravanSupportChatbotInputSchema>;

const CaravanSupportChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the user question.'),
  youtubeLink: z.string().optional().nullable().describe('An optional YouTube link that provides more information about the answer.'),
  relatedArticleTitle: z.string().optional().nullable().describe('The title of a related article from the Support Center, if applicable.')
});
export type CaravanSupportChatbotOutput = z.infer<typeof CaravanSupportChatbotOutputSchema>;

// Simple FAQ knowledge base
const faqData = [
  { 
    keywords: ["tyre pressure", "tire pressure", "tyres", "tires"], 
    answer: "Caravan tyre pressures are crucial for safety and tyre life. They typically range from 40-65 PSI, but always check the caravan's tyre placard or the tyre manufacturer's specific recommendations for your model and load. Tow vehicle tyre pressures should also be adjusted as per its placard, especially when towing." 
  },
  { 
    keywords: ["awning setup", "set up awning", "deploy awning"], 
    answer: "To set up your caravan awning: 1. Unlock any travel locks. 2. Use the awning rod to hook the pull strap and roll the awning out. 3. Extend the support legs and position them vertically or against the caravan wall. 4. Secure the legs. 5. Tension the fabric using the rafters or tensioning knobs. Ensure it's well-secured, especially if wind is expected." 
  },
  { 
    keywords: ["battery flat", "battery dead", "charge battery"], 
    answer: "If your caravan battery is flat: 1. Check if it's an issue with the charger or a blown fuse. 2. Try charging it using your tow vehicle (if set up for it), a 240V smart charger when connected to mains power, or a solar panel. 3. If it's an old battery, it might need replacement. Deep cycle batteries can be damaged if left flat for too long." 
  },
  {
    keywords: ["toilet cassette", "empty toilet"],
    answer: "To empty your caravan toilet cassette: 1. Ensure the blade valve is closed. 2. Remove the cassette from its external hatch. 3. Transport it to an approved dump point. 4. Unscrew the spout, point it downwards into the dump point, and press the air vent button to empty smoothly. 5. Rinse the cassette with water. 6. Add the appropriate toilet chemical before reinserting."
  },
  {
    keywords: ["sway control", "caravan swaying"],
    answer: "Caravan sway can be dangerous. To prevent it: 1. Ensure correct weight distribution (approx 10-15% of caravan ATM on the towball). 2. Don't overload the rear of the caravan. 3. Check tyre pressures. 4. Drive at appropriate speeds for conditions. 5. Consider using a weight distribution hitch and/or an electronic sway control system. If sway occurs, gently ease off the accelerator and apply the caravan's electric brakes manually (if fitted with a controller that allows this) – do not slam on the vehicle brakes or turn the steering wheel sharply."
  }
];

const getFaqAnswer = ai.defineTool(
  {
    name: 'getFaqAnswer',
    description: 'Retrieves a pre-defined answer to a frequently asked caravanning question from the local knowledge base. Use this tool first to check for existing answers.',
    inputSchema: z.object({
      topicKeywords: z.string().describe('One or more keywords from the user question related to the topic they are asking about (e.g., "tyre pressure", "awning setup").'),
    }),
    outputSchema: z.string().optional().describe('The answer from the FAQ if a match is found, otherwise undefined.'),
  },
  async ({ topicKeywords }) => {
    const lowerTopicKeywords = topicKeywords.toLowerCase().split(/\s+/).filter(kw => kw.length > 2); // Split into words
    for (const faq of faqData) {
      if (faq.keywords.some(kw => lowerTopicKeywords.some(userKw => kw.toLowerCase().includes(userKw)))) {
        return faq.answer;
      }
    }
    return undefined; // No specific FAQ found
  }
);

const getArticleInfoTool = ai.defineTool(
  {
    name: 'getArticleInfoTool',
    description: 'Searches the static article database for relevant information based on user keywords. Use this if no direct FAQ answer is found.',
    inputSchema: z.object({
      searchKeywords: z.string().describe('Keywords from the user question to find a relevant article (e.g., "parking caravan", "battery management").'),
    }),
    outputSchema: z.object({
      title: z.string(),
      summary: z.string(), // The introduction of the article
      topic: z.string(),
    }).optional().describe('The title, introduction (as summary), and topic of a relevant article if found, otherwise undefined.'),
  },
  async ({ searchKeywords }) => {
    const lowerKeywords = searchKeywords.toLowerCase().split(/\s+/).filter(kw => kw.length > 2); // Split into words, ignore small words
    if (lowerKeywords.length === 0) return undefined;

    for (const article of staticCaravanningArticles) {
      const searchableText = `${article.topic.toLowerCase()} ${article.title.toLowerCase()} ${article.introduction.toLowerCase()}`;
      if (lowerKeywords.every(kw => searchableText.includes(kw))) { // All keywords must be present
        return {
          title: article.title,
          summary: article.introduction,
          topic: article.topic,
        };
      }
    }
    // Fallback: check if any keyword matches
     for (const article of staticCaravanningArticles) {
      const searchableText = `${article.topic.toLowerCase()} ${article.title.toLowerCase()} ${article.introduction.toLowerCase()}`;
      if (lowerKeywords.some(kw => searchableText.includes(kw))) {
        return {
          title: article.title,
          summary: article.introduction,
          topic: article.topic,
        };
      }
    }
    return undefined;
  }
);


const findYoutubeLink = ai.defineTool(
  {
    name: 'findYoutubeLink',
    description: 'Finds a relevant YouTube video link based on the user question topic. Use this if a visual explanation would be helpful.',
    inputSchema: z.object({
      searchQuery: z.string().describe('A concise search query based on the user question to find a relevant YouTube video.'),
    }),
    outputSchema: z.string().optional(),
  },
  async (input) => {
    // This is a placeholder implementation.
    if (input.searchQuery.toLowerCase().includes('weight limits')) {
      return 'https://www.youtube.com/watch?v=M7lc1UVf-VE';
    }
    if (input.searchQuery.toLowerCase().includes('awning')) {
        return 'https://www.youtube.com/watch?v=L_jWHffIx5E';
    }
    return undefined;
  }
);

export async function caravanSupportChatbot(input: CaravanSupportChatbotInput): Promise<CaravanSupportChatbotOutput> {
  return caravanSupportChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'caravanSupportChatbotPrompt',
  input: {schema: CaravanSupportChatbotInputSchema},
  output: {schema: CaravanSupportChatbotOutputSchema},
  tools: [getFaqAnswer, getArticleInfoTool, findYoutubeLink],
  prompt: `You are a friendly and helpful caravan support chatbot for KamperHub. Your primary goal is to provide accurate and useful answers to user questions about caravanning, prioritizing information from KamperHub's own knowledge base.

When a user asks a question:
1.  **Prioritize Internal Knowledge:** First, use the 'getFaqAnswer' tool with relevant keywords from the user's question.
2.  **If FAQ Answer Found:** If 'getFaqAnswer' returns an answer, use this as the core of your response. You can rephrase it conversationally but ensure the factual content comes from the tool. Set 'relatedArticleTitle' to null.
3.  **If No FAQ Answer, Check Articles:** If 'getFaqAnswer' does *not* return an answer, then use the 'getArticleInfoTool' with keywords from the user's question to search our published articles.
4.  **If Article Found:** If 'getArticleInfoTool' returns an article (title, summary, topic), base your answer on the provided 'summary'. Set the 'relatedArticleTitle' output field to the article's 'title'. You can also mention that more details are available in the article "[Article Title]" in our Support Center.
5.  **Last Resort - General Knowledge:** ONLY if BOTH 'getFaqAnswer' AND 'getArticleInfoTool' provide no specific, relevant answer or information for the user's question, then you may answer the question using your general knowledge about caravanning. In this case, set 'relatedArticleTitle' to null.
6.  **Optional YouTube Link:** Regardless of how the answer was sourced (FAQ, Article, or General Knowledge), if you believe a YouTube video would be genuinely helpful to the user, use the 'findYoutubeLink' tool with a relevant search query and include the link in the 'youtubeLink' output field. Otherwise, set 'youtubeLink' to null.

Strictly follow this order of operations. Do not use general knowledge if internal tools can provide an answer.

User's Question: {{{question}}}
`,
});

const caravanSupportChatbotFlow = ai.defineFlow(
  {
    name: 'caravanSupportChatbotFlow',
    inputSchema: CaravanSupportChatbotInputSchema,
    outputSchema: CaravanSupportChatbotOutputSchema,
  },
  async (input): Promise<CaravanSupportChatbotOutput> => {
    try {
      const {output, usage} = await prompt(input); // Include usage for detailed logging
      
      // Log the raw output from the model for easier debugging
      console.log('CaravanSupportChatbotFlow: Raw AI model output:', JSON.stringify(output, null, 2));
      console.log('CaravanSupportChatbotFlow: AI model usage:', JSON.stringify(usage, null, 2));


      if (!output) {
        console.warn('CaravanSupportChatbotFlow: AI model returned null output. This might be due to schema mismatch or other non-fatal errors from the model.');
        return { 
          answer: "I'm sorry, I had trouble generating a response in the expected format. Could you try rephrasing your question?", 
          youtubeLink: null,
          relatedArticleTitle: null,
        };
      }
      
      // Validate output against schema more explicitly if needed, though Genkit usually handles this.
      // For now, assume output structure is mostly correct if not null.
      
      return {
        answer: output.answer || "I'm not sure how to respond to that. Can you try asking differently?", // Fallback if answer is empty
        youtubeLink: output.youtubeLink || null,
        relatedArticleTitle: output.relatedArticleTitle || null,
      };
    } catch (error: any) {
      console.error("Error in caravanSupportChatbotFlow calling prompt:", error);
      console.error("Prompt Error Details:", {
        message: error.message,
        stack: error.stack,
        cause: error.cause, // Might contain more specific info from underlying API
        name: error.name,
      });
      if (error.cause && typeof error.cause === 'object') {
        console.error("Prompt Error Cause Object:", JSON.stringify(error.cause, Object.getOwnPropertyNames(error.cause)));
      }

      let answer = "An unexpected error occurred while communicating with the AI assistant. Please try again later.";
      if (error.message) {
        const errorMessage = error.message.toLowerCase();
        if (errorMessage.includes("service unavailable") || errorMessage.includes("overloaded") || errorMessage.includes("model is overloaded") || (error.cause && typeof error.cause === 'object' && 'status' in error.cause && error.cause.status === 503) ) {
          answer = "The AI assistant is currently experiencing high demand or is temporarily unavailable. Please try again in a few moments.";
        } else if (errorMessage.includes("429") || errorMessage.includes("quota") || errorMessage.includes("rate limit") || (error.cause && typeof error.cause === 'object' && 'status' in error.cause && error.cause.status === 429)) {
          answer = "The AI assistant has hit a usage limit for the current period. Please try again later. If this issue persists, please check API plan details.";
        } else if (errorMessage.includes("api key not valid") || (error.cause && typeof error.cause === 'object' && 'status' in error.cause && (error.cause.status === 401 || error.cause.status === 403)) ){
           answer = "There seems to be an issue with the AI service configuration (e.g. API key). Please contact support if this persists.";
        } else if (errorMessage.includes("failed to parse schema") || errorMessage.includes("output_schema")) {
           answer = "I had a little trouble formatting my thoughts. Could you try asking in a slightly different way?";
        }
      }
      
      return { 
        answer: answer, 
        youtubeLink: null,
        relatedArticleTitle: null,
      };
    }
  }
);

