// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A caravan support chatbot AI agent.
 *
 * - caravanSupportChatbot - A function that handles the chatbot interaction.
 * - CaravanSupportChatbotInput - The input type for the caravanSupportChatbot function.
 * - CaravanSupportChatbotOutput - The return type for the caravanSupportChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';
import { staticCaravanningArticles, type AiGeneratedArticle } from '@/types/learn';
import { getFirebaseAdmin } from '@/lib/firebase-admin';
import type { LoggedTrip } from '@/types/tripplanner';
import type { Expense } from '@/types/expense';
import type { StoredVehicle } from '@/types/vehicle';


const CaravanSupportChatbotInputSchema = z.object({
  question: z.string().describe('The question asked by the user about caravanning.'),
});
export type CaravanSupportChatbotInput = z.infer<typeof CaravanSupportChatbotInputSchema>;

const CaravanSupportChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the user question.'),
  youtubeLink: z.string().optional().nullable().describe('An optional YouTube link that provides more information about the answer.'),
  relatedArticleTitle: z.string().optional().nullable().describe('The title of a related article from the Support Center, if applicable.')
});
export type CaravanSupportChatbotOutput = z.infer<typeof CaravanSupportChatbotOutputSchema>;

// Simple FAQ knowledge base
const faqData = [
  { 
    keywords: ["tyre pressure", "tire pressure", "tyres", "tires"], 
    answer: "Caravan tyre pressures are crucial for safety and tyre life. They typically range from 40-65 PSI, but always check the caravan's tyre placard or the tyre manufacturer's specific recommendations for your model and load. Tow vehicle tyre pressures should also be adjusted as per its placard, especially when towing." 
  },
  { 
    keywords: ["awning setup", "set up awning", "deploy awning"], 
    answer: "To set up your caravan awning: 1. Unlock any travel locks. 2. Use the awning rod to hook the pull strap and roll the awning out. 3. Extend the support legs and position them vertically or against the caravan wall. 4. Secure the legs. 5. Tension the fabric using the rafters or tensioning knobs. Ensure it's well-secured, especially if wind is expected." 
  },
  { 
    keywords: ["battery flat", "battery dead", "charge battery"], 
    answer: "If your caravan battery is flat: 1. Check if it's an issue with the charger or a blown fuse. 2. Try charging it using your tow vehicle (if set up for it), a 240V smart charger when connected to mains power, or a solar panel. 3. If it's an old battery, it might need replacement. Deep cycle batteries can be damaged if left flat for too long." 
  },
  {
    keywords: ["toilet cassette", "empty toilet"],
    answer: "To empty your caravan toilet cassette: 1. Ensure the blade valve is closed. 2. Remove the cassette from its external hatch. 3. Transport it to an approved dump point. 4. Unscrew the spout, point it downwards into the dump point, and press the air vent button to empty smoothly. 5. Rinse the cassette with water. 6. Add the appropriate toilet chemical before reinserting."
  },
  {
    keywords: ["sway control", "caravan swaying"],
    answer: "Caravan sway can be dangerous. To prevent it: 1. Ensure correct weight distribution (approx 10-15% of caravan ATM on the towball). 2. Don't overload the rear of the caravan. 3. Check tyre pressures. 4. Drive at appropriate speeds for conditions. 5. Consider using a weight distribution hitch and/or an electronic sway control system. If sway occurs, gently ease off the accelerator and apply the caravan's electric brakes manually (if fitted with a controller that allows this) – do not slam on the vehicle brakes or turn the steering wheel sharply."
  }
];

const getFaqAnswer = ai.defineTool(
  {
    name: 'getFaqAnswer',
    description: 'Retrieves a pre-defined answer to a frequently asked caravanning question from the local knowledge base. Use this tool first to check for existing answers.',
    inputSchema: z.object({
      topicKeywords: z.string().describe('One or more keywords from the user question related to the topic they are asking about (e.g., "tyre pressure", "awning setup").'),
    }),
    outputSchema: z.string().optional().describe('The answer from the FAQ if a match is found, otherwise undefined.'),
  },
  async ({ topicKeywords }) => {
    const lowerTopicKeywords = topicKeywords.toLowerCase().split(/\s+/).filter(kw => kw.length > 2); // Split into words
    for (const faq of faqData) {
      if (faq.keywords.some(kw => lowerTopicKeywords.some(userKw => kw.toLowerCase().includes(userKw)))) {
        return faq.answer;
      }
    }
    return undefined; // No specific FAQ found
  }
);

const getArticleInfoTool = ai.defineTool(
  {
    name: 'getArticleInfoTool',
    description: 'Searches the static article database for relevant information based on user keywords. Use this if no direct FAQ answer is found.',
    inputSchema: z.object({
      searchKeywords: z.string().describe('Keywords from the user question to find a relevant article (e.g., "parking caravan", "battery management").'),
    }),
    outputSchema: z.object({
      title: z.string(),
      summary: z.string(), // The introduction of the article
      topic: z.string(),
    }).optional().describe('The title, introduction (as summary), and topic of a relevant article if found, otherwise undefined.'),
  },
  async ({ searchKeywords }) => {
    const lowerKeywords = searchKeywords.toLowerCase().split(/\s+/).filter(kw => kw.length > 2); // Split into words, ignore small words
    if (lowerKeywords.length === 0) return undefined;

    for (const article of staticCaravanningArticles) {
      const searchableText = `${article.topic.toLowerCase()} ${article.title.toLowerCase()} ${article.introduction.toLowerCase()}`;
      if (lowerKeywords.every(kw => searchableText.includes(kw))) { // All keywords must be present
        return {
          title: article.title,
          summary: article.introduction,
          topic: article.topic,
        };
      }
    }
    // Fallback: check if any keyword matches
     for (const article of staticCaravanningArticles) {
      const searchableText = `${article.topic.toLowerCase()} ${article.title.toLowerCase()} ${article.introduction.toLowerCase()}`;
      if (lowerKeywords.some(kw => searchableText.includes(kw))) {
        return {
          title: article.title,
          summary: article.introduction,
          topic: article.topic,
        };
      }
    }
    return undefined;
  }
);


const findYoutubeLink = ai.defineTool(
  {
    name: 'findYoutubeLink',
    description: 'Finds a relevant YouTube video link based on the user question topic. Use this if a visual explanation would be helpful.',
    inputSchema: z.object({
      searchQuery: z.string().describe('A concise search query based on the user question to find a relevant YouTube video.'),
    }),
    outputSchema: z.string().optional(),
  },
  async (input) => {
    // This is a placeholder implementation.
    if (input.searchQuery.toLowerCase().includes('weight limits')) {
      return 'https://www.youtube.com/watch?v=M7lc1UVf-VE';
    }
    if (input.searchQuery.toLowerCase().includes('awning')) {
        return 'https://www.youtube.com/watch?v=L_jWHffIx5E';
    }
    return undefined;
  }
);

const listUserTripsTool = ai.defineTool(
  {
    name: 'listUserTrips',
    description: "Lists all of the user's available trips.",
    inputSchema: z.object({
      userId: z.string().describe("The user's unique ID."),
    }),
    outputSchema: z.array(z.string()).describe("A list of trip names.").nullable(),
  },
  async ({ userId }) => {
    const { firestore, error } = getFirebaseAdmin();
    if (error || !firestore) return null;
    try {
      const tripsRef = firestore.collection('users').doc(userId).collection('trips');
      const snapshot = await tripsRef.get();
      if (snapshot.empty) return null;

      const tripNames = snapshot.docs
        .map(doc => doc.data()?.name)
        .filter((name): name is string => typeof name === 'string');
      
      return tripNames.length > 0 ? tripNames : null;
    } catch (e: any) {
        console.error('Critical error in listUserTripsTool:', e);
        return null;
    }
  }
);

const listUserVehiclesTool = ai.defineTool(
  {
    name: 'listUserVehicles',
    description: "Lists all of the user's saved vehicles.",
    inputSchema: z.object({
      userId: z.string().describe("The user's unique ID."),
    }),
    outputSchema: z.array(z.string()).describe("A list of vehicle names (e.g., '2022 Ford Ranger').").nullable(),
  },
  async ({ userId }) => {
    const { firestore, error } = getFirebaseAdmin();
    if (error || !firestore) return null;
    try {
      const vehiclesRef = firestore.collection('users').doc(userId).collection('vehicles');
      const snapshot = await vehiclesRef.get();
      if (snapshot.empty) return null;

      const vehicleNames = snapshot.docs
        .map(doc => {
            const data = doc.data() as StoredVehicle;
            return data.year && data.make && data.model ? `${data.year} ${data.make} ${data.model}` : null;
        })
        .filter((name): name is string => name !== null);
      
      return vehicleNames.length > 0 ? vehicleNames : null;
    } catch (e: any) {
        console.error('Critical error in listUserVehiclesTool:', e);
        return null;
    }
  }
);


const findUserTripTool = ai.defineTool(
  {
    name: 'findUserTrip',
    description: "Finds a user's trip by its name to get its ID and budget categories. Use this before trying to add an expense.",
    inputSchema: z.object({
      userId: z.string().describe("The user's unique ID."),
      tripName: z.string().describe('A partial or full name of the trip to search for.'),
    }),
    outputSchema: z.object({
      tripId: z.string(),
      tripName: z.string(),
      budgetCategories: z.array(z.string()),
    }).nullable(),
  },
  async ({ userId, tripName }) => {
    const { firestore, error } = getFirebaseAdmin();
    if (error || !firestore) return null;
    try {
      const tripsRef = firestore.collection('users').doc(userId).collection('trips');
      const snapshot = await tripsRef.get();
      if (snapshot.empty) {
        return null;
      }

      const trips: LoggedTrip[] = [];
      snapshot.docs.forEach(doc => {
        const data = doc.data();
        if (data && typeof data.name === 'string' && typeof data.id === 'string') {
          trips.push(data as LoggedTrip);
        }
      });
      
      const foundTrip = trips.find(trip => trip.name.toLowerCase().includes(tripName.toLowerCase()));

      if (foundTrip) {
        return {
          tripId: foundTrip.id,
          tripName: foundTrip.name,
          budgetCategories: foundTrip.budget?.map(cat => cat.name) || [],
        };
      }
      return null;
    } catch (e: any) {
        console.error('Critical error in findUserTripTool:', e);
        return null; 
    }
  }
);

const addExpenseToTripTool = ai.defineTool(
  {
    name: 'addExpenseToTrip',
    description: 'Adds an expense record to a specific trip for a user.',
    inputSchema: z.object({
      userId: z.string().describe("The user's unique ID."),
      tripId: z.string().describe("The unique ID of the trip, obtained from findUserTrip."),
      amount: z.number().describe("The monetary value of the expense."),
      categoryName: z.string().describe("The name of the budget category for this expense."),
      description: z.string().describe("A brief description of the expense (e.g., 'Diesel fill-up', 'Groceries at Coles')."),
      expenseDate: z.string().datetime().describe("The date of the expense in ISO 8601 format."),
    }),
    outputSchema: z.string().describe("A confirmation message indicating success or failure."),
  },
  async ({ userId, tripId, amount, categoryName, description, expenseDate }) => {
    const { firestore, error } = getFirebaseAdmin();
    if (error || !firestore) return 'Error: Database service is not available.';
    
    const tripRef = firestore.collection('users').doc(userId).collection('trips').doc(tripId);
    
    try {
      const doc = await tripRef.get();
      if (!doc.exists) {
        return `Error: Trip with ID ${tripId} not found.`;
      }
      const trip = doc.data() as LoggedTrip;

      const budgetCategory = trip.budget?.find(cat => cat.name.toLowerCase() === categoryName.toLowerCase());
      if (!budgetCategory) {
        const availableCategories = trip.budget?.map(c => c.name).join(', ') || 'none';
        return `Error: Budget category "${categoryName}" not found. Please choose from: ${availableCategories}.`;
      }

      const newExpense: Omit<Expense, 'tripId'> = {
        id: Date.now().toString(),
        categoryId: budgetCategory.id,
        amount,
        description,
        date: expenseDate,
        timestamp: new Date().toISOString(),
      };

      const updatedExpenses = [...(trip.expenses || []), newExpense];
      
      await tripRef.update({ expenses: updatedExpenses });

      return `Successfully added expense "${description}" for $${amount.toFixed(2)} to the trip "${trip.name}".`;

    } catch (e: any) {
      console.error("Error adding expense to trip:", e);
      return `An unexpected error occurred while adding the expense: ${e.message}`;
    }
  }
);

const getTripExpensesTool = ai.defineTool(
  {
    name: 'getTripExpenses',
    description: "Retrieves all expenses for a specific trip, optionally filtered by category. Use this to answer questions about spending.",
    inputSchema: z.object({
      userId: z.string().describe("The user's unique ID."),
      tripId: z.string().describe("The unique ID of the trip, obtained from findUserTrip."),
      categoryName: z.string().optional().describe("An optional category name to filter expenses by (e.g., 'Fuel', 'Accommodation')."),
    }),
    outputSchema: z.object({
      totalSpend: z.number(),
      expenses: z.array(z.object({
        description: z.string(),
        amount: z.number(),
        category: z.string(),
        date: z.string(),
      })),
    }).nullable(),
  },
  async ({ userId, tripId, categoryName }) => {
    const { firestore, error } = getFirebaseAdmin();
    if (error || !firestore) return null;

    try {
      const tripRef = firestore.collection('users').doc(userId).collection('trips').doc(tripId);
      const tripDoc = await tripRef.get();

      if (!tripDoc.exists) {
        return null;
      }

      const trip = tripDoc.data() as LoggedTrip;
      let expenses = trip.expenses || [];

      const categoryMap = new Map(trip.budget?.map(cat => [cat.id, cat.name]) || []);

      if (categoryName) {
        const categoryId = trip.budget?.find(cat => cat.name.toLowerCase() === categoryName.toLowerCase())?.id;
        if (categoryId) {
          expenses = expenses.filter(exp => exp.categoryId === categoryId);
        } else {
          // If category doesn't exist, return empty results for that category.
          return { totalSpend: 0, expenses: [] };
        }
      }
      
      const totalSpend = expenses.reduce((sum, exp) => sum + exp.amount, 0);

      const formattedExpenses = expenses.map(exp => ({
        description: exp.description,
        amount: exp.amount,
        category: categoryMap.get(exp.categoryId) || 'Unknown',
        date: exp.date,
      }));

      return { totalSpend, expenses: formattedExpenses };
    } catch (e: any) {
      console.error('Critical error in getTripExpensesTool:', e);
      return null;
    }
  }
);

const addAmountToBudgetCategoryTool = ai.defineTool(
  {
    name: 'addAmountToBudgetCategory',
    description: 'Adds a specified amount to a budget category for a trip. If the category does not exist, it will be created.',
    inputSchema: z.object({
      userId: z.string().describe("The user's unique ID."),
      tripId: z.string().describe("The unique ID of the trip, obtained from findUserTrip."),
      categoryName: z.string().describe("The name of the budget category to add the amount to (e.g., 'Food', 'Activities')."),
      amountToAdd: z.number().positive().describe("The positive amount to add to the budget category."),
    }),
    outputSchema: z.string().describe("A confirmation message indicating success or failure."),
  },
  async ({ userId, tripId, categoryName, amountToAdd }) => {
    const { firestore, error } = getFirebaseAdmin();
    if (error || !firestore) return 'Error: Database service is not available.';
    
    const tripRef = firestore.collection('users').doc(userId).collection('trips').doc(tripId);
    
    try {
      await firestore.runTransaction(async (transaction) => {
        const doc = await transaction.get(tripRef);
        if (!doc.exists) {
          throw new Error(`Trip with ID ${tripId} not found.`);
        }
        const trip = doc.data() as LoggedTrip;
        const budget = trip.budget || [];

        const categoryIndex = budget.findIndex(cat => cat.name.toLowerCase() === categoryName.toLowerCase());

        if (categoryIndex > -1) {
          // Category exists, update it
          budget[categoryIndex].budgetedAmount += amountToAdd;
        } else {
          // Category doesn't exist, create it
          budget.push({
            id: `budget_${categoryName.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}`,
            name: categoryName,
            budgetedAmount: amountToAdd,
          });
        }
        
        transaction.update(tripRef, { budget });
      });

      return `Successfully added $${amountToAdd.toFixed(2)} to the "${categoryName}" budget for the trip.`;

    } catch (e: any) {
      console.error("Error adding to budget category:", e);
      return `An unexpected error occurred while updating the budget: ${e.message}`;
    }
  }
);


export async function caravanSupportChatbot(
  input: CaravanSupportChatbotInput,
  userId: string,
): Promise<CaravanSupportChatbotOutput> {
  return caravanSupportChatbotFlow({ ...input, userId });
}

const CaravanSupportChatbotFlowInputSchema = CaravanSupportChatbotInputSchema.extend({
  userId: z.string(),
});

const prompt = ai.definePrompt({
  name: 'caravanSupportChatbotPrompt',
  input: {schema: CaravanSupportChatbotFlowInputSchema },
  output: {schema: CaravanSupportChatbotOutputSchema},
  tools: [getFaqAnswer, getArticleInfoTool, findYoutubeLink, listUserTripsTool, findUserTripTool, addExpenseToTripTool, getTripExpensesTool, addAmountToBudgetCategoryTool, listUserVehiclesTool],
  prompt: `You are a friendly and helpful caravan support chatbot for KamperHub. Your goal is to provide useful answers and perform actions for the user.

USER ID: {{{userId}}}

**Response Hierarchy:**
1.  **Data Listing Intent:** If the user asks a general question like "what trips do I have?" or "what vehicles do I have?", use the 'listUserTripsTool' or 'listUserVehiclesTool' respectively. Present the list clearly to the user. If the tool returns null, inform the user they have no items logged.
2.  **Action or Query Intent:** First, check if the user wants to perform an action (e.g., "add expense", "increase budget") or query their data (e.g., "how much did I spend?"). If so, proceed to the "Data Interaction" section below.
3.  **FAQ Check:** If it's a general question, use 'getFaqAnswer' first.
4.  **Article Check:** If no FAQ is found, use 'getArticleInfoTool'.
5.  **General Knowledge:** If no internal tools provide an answer, use your general caravanning knowledge.
6.  **YouTube Link:** As a final step, if a video would be helpful, use 'findYoutubeLink'.

**Data Interaction (Budget & Expenses):**
- **Identify Intent:** Recognize if the user wants to *add/modify budget*, *add* an expense, or *get* expense information.
- **Find Trip:** For any budget or expense-related action, you MUST find the trip first. If the user mentions a trip name (e.g., "Fraser Island trip"), use the 'findUserTripTool' with the user's ID and the trip name.
    - If the tool returns null, it means no matching trip was found. You MUST inform the user that you couldn't find that trip and ask them to try a different name or check their trip log. Do not proceed.
    - If the user doesn't mention a trip name, you must ask them for it.

**If Adding/Modifying Budget:**
1.  **Gather Details:** You need the trip ID, the amount, and the category name. If any of these are missing from the user's request, you MUST ask for them. For example, if they say "add $50 to the budget for my trip", you must ask "For which category?".
2.  **Add to Budget:** Once all details are gathered, use the 'addAmountToBudgetCategory' tool with all the details (userId, tripId, categoryName, amountToAdd).
3.  **Confirm:** Relay the success or error message from the tool back to the user.

**If Adding an Expense:**
1.  **Gather Details:** Once you have the trip ID, you need the expense details: amount, description, and category. If any of these are missing from the user's request, ask for them. When asking for a category, you can suggest the available categories returned by 'findUserTripTool'.
2.  **Get Date:** Always assume today's date for the expense unless the user specifies otherwise. Format it as an ISO 8601 string.
3.  **Add Expense:** Use the 'addExpenseToTripTool' with all the gathered details (userId, tripId, amount, categoryName, description, expenseDate).
4.  **Confirm:** Relay the success or error message from the tool back to the user in a conversational way.

**If Retrieving Expenses:**
1.  **Identify Category (Optional):** Check if the user mentioned a specific category (e.g., "how much for fuel?").
2.  **Get Expenses:** Use the 'getTripExpenses' tool with the userId, tripId, and the optional category name.
3.  **Summarize:** If the tool returns data, summarize it for the user (e.g., "For your 'Fraser Island' trip, you've spent a total of $X. Here are the expenses..."). If the total spend is zero, inform them no expenses were found for that trip/category.

Strictly follow these hierarchies. For action-based requests, focus only on completing the action and do not suggest YouTube links or related articles.

User's Question: {{{question}}}
`,
});

const caravanSupportChatbotFlow = ai.defineFlow(
  {
    name: 'caravanSupportChatbotFlow',
    inputSchema: CaravanSupportChatbotFlowInputSchema,
    outputSchema: CaravanSupportChatbotOutputSchema,
  },
  async (input): Promise<CaravanSupportChatbotOutput> => {
    try {
      const {output} = await prompt(input);
      if (!output) {
        throw new Error('The AI returned an empty or invalid response.');
      }
      return output;
    } catch (error: any) {
      console.error("Error in caravanSupportChatbotFlow:", error);
      let answer = `I'm sorry, I ran into a problem. Here is the technical error: ${error.message || 'An unknown error occurred.'}`;
      if (error.message && error.message.includes('API_KEY_HTTP_REFERRER_BLOCKED')) {
        answer = 'AI Service Error: The GOOGLE_API_KEY has "HTTP referrer" restrictions, which is not allowed for server-to-server AI calls. Use a key with "None" or "IP Address" restrictions as explained in the setup guide.';
      }
      return {
        answer: answer,
        youtubeLink: null,
        relatedArticleTitle: null,
      };
    }
  }
);
